// Talent Management & HR Solutions Services Data
const talentManagementHRServices = [
  {
    id: "recruitment",
    title: "Recruitment & Selection",
    description: "Role profiling, competency-based interviews, and reference checks to cut time-to-hire and improve cultural/technical fit.",
    image: "/images/home/hr-recruitment.png",
    imageAlt: "Recruitment and selection service",
    tag: "HR",
    tagClass: "tag-training",
    schedule: "On-Demand",
    location: "On-site / Remote",
    link: "/talent-management-hr-solution/recruitment-selection.html",
    bookingLink: "/booking.html",
    proposalLink: "/proposal.html"
  },
  {
    id: "training",
    title: "Training & Development",
    description: "Tailored corporate programs that boost employee skills, productivity, and leadership capacity through structured learning pathways.",
    image: "/images/home/professional-training.png",
    imageAlt: "Training and development service",
    tag: "Development",
    tagClass: "tag-training",
    schedule: "Flexible Scheduling",
    location: "On-site / Remote",
    link: "/talent-management-hr-solution/training-development.html",
    bookingLink: "/booking.html",
    proposalLink: "/proposal.html"
  },
  {
    id: "outsourcing",
    title: "Talent & Payroll Outsourcing",
    description: "Contracts, pay runs, statutory remittances (PAYE, Pension, NHF), onboarding, and HRIS—handled end-to-end.",
    image: "/images/home/payroll-outsourcing.png",
    imageAlt: "Talent and payroll outsourcing service",
    tag: "Outsourcing",
    tagClass: "tag-strategy",
    schedule: "Monthly / Weekly Cycles",
    location: "Nigeria & Remote",
    link: "/talent-management-hr-solution/talent-payroll-outsourcing.html",
    bookingLink: "/booking.html",
    proposalLink: "/proposal.html"
  },
  {
    id: "verification",
    title: "Background Checks & Verification",
    description: "Employment history, guarantor, criminal & credit checks with tamper-proof reports and SLAs.",
    image: "/images/home/background-checks.png",
    imageAlt: "Background checks and verification service",
    tag: "Compliance",
    tagClass: "tag-operations",
    schedule: "2–7 Business Days",
    location: "National / Global",
    link: "/talent-management-hr-solution/background-checks-verification.html",
    bookingLink: "/booking.html",
    proposalLink: "/proposal.html"
  },
  {
    id: "policies",
    title: "HR Policies & Employee Handbook",
    description: "Clear, transparent policies that align people with business goals and ensure compliance with labor regulations.",
    image: "/images/home/hr-management.png",
    imageAlt: "HR policies and employee handbook service",
    tag: "Compliance",
    tagClass: "tag-operations",
    schedule: "Project-based",
    location: "On-site / Remote",
    link: "/talent-management-hr-solution/hr-policies-employee-handbook.html",
    bookingLink: "/booking.html",
    proposalLink: "/proposal.html"
  },
  {
    id: "career",
    title: "Career Services",
    description: "CV, LinkedIn, and professional profile optimization for global opportunities and career transitions.",
    image: "/images/home/hr-recruitment.png",
    imageAlt: "Career services",
    tag: "Career",
    tagClass: "tag-training",
    schedule: "On-Demand",
    location: "Remote",
    link: "/talent-management-hr-solution/career-service.html",
    bookingLink: "/booking.html",
    proposalLink: "/proposal.html"
  }
];

// Business Development & Strategy Services Data
const businessDevelopmentServices = [
  {
    id: "research",
    title: "Market Research & Business Analysis",
    description: "Data-driven insights to guide smarter business decisions through comprehensive market analysis and competitive intelligence.",
    image: "/images/home/market-research.png",
    imageAlt: "Market research and business analysis service",
    tag: "Strategy",
    tagClass: "tag-strategy",
    schedule: "Project-based",
    location: "On-site / Remote",
    link: "/business-development/market-research-business-analysis.html",
    bookingLink: "/booking.html",
    proposalLink: "/proposal.html"
  },
  {
    id: "model",
    title: "Business Model & Structure Design",
    description: "Build scalable frameworks for long-term success with clear revenue models and organizational structures.",
    image: "/images/home/business-model.png",
    imageAlt: "Business model and structure design service",
    tag: "Strategy",
    tagClass: "tag-strategy",
    schedule: "Project-based",
    location: "On-site / Remote",
    link: "/business-development/business-model-structure-design.html",
    bookingLink: "/booking.html",
    proposalLink: "/proposal.html"
  },
  {
    id: "execution",
    title: "Corporate Strategy & Execution",
    description: "Align vision, people, and processes for measurable results with actionable strategic plans.",
    image: "/images/home/corporate-strategy.png",
    imageAlt: "Corporate strategy and execution service",
    tag: "Strategy",
    tagClass: "tag-strategy",
    schedule: "Project-based",
    location: "On-site / Remote",
    link: "/business-development/corporate-strategy-execution.html",
    bookingLink: "/booking.html",
    proposalLink: "/proposal.html"
  },
  {
    id: "branding",
    title: "Corporate Branding",
    description: "Create powerful, trust-building brand identities that resonate with your target audience.",
    image: "/images/home/business-development.png",
    imageAlt: "Corporate branding service",
    tag: "Branding",
    tagClass: "tag-strategy",
    schedule: "Project-based",
    location: "On-site / Remote",
    link: "/business-development/corporate-branding.html",
    bookingLink: "/booking.html",
    proposalLink: "/proposal.html"
  },
  {
    id: "optimization",
    title: "Business Process Optimization",
    description: "Streamline operations and eliminate inefficiencies to improve productivity and reduce costs.",
    image: "/images/home/end-to-end-execution.png",
    imageAlt: "Business process optimization service",
    tag: "Operations",
    tagClass: "tag-operations",
    schedule: "Project-based",
    location: "On-site / Remote",
    link: "/business-development/business-process-optimization.html",
    bookingLink: "/booking.html",
    proposalLink: "/proposal.html"
  },
  {
    id: "valuation",
    title: "Financial Modeling & Valuation",
    description: "Gain clarity on investments and performance with comprehensive financial models and valuations.",
    image: "/images/home/data-analytics.png",
    imageAlt: "Financial modeling and valuation service",
    tag: "Finance",
    tagClass: "tag-strategy",
    schedule: "Project-based",
    location: "On-site / Remote",
    link: "/business-development/financial-modeling-valuation.html",
    bookingLink: "/booking.html",
    proposalLink: "/proposal.html"
  },
  {
    id: "audit",
    title: "Auditing & Reconciliation",
    description: "Ensure compliance, accuracy, and accountability with independent audits and financial reconciliation.",
    image: "/images/home/compliance-by-first.png",
    imageAlt: "Auditing and reconciliation service",
    tag: "Compliance",
    tagClass: "tag-operations",
    schedule: "Project-based",
    location: "On-site / Remote",
    link: "/business-development/auditing-reconciliation.html",
    bookingLink: "/booking.html",
    proposalLink: "/proposal.html"
  }
];

// Professional Training Programmes Data
const professionalTrainingServices = [
  {
    id: "leadership",
    title: "Leadership & Management",
    description: "Develop emotionally intelligent leaders who inspire performance and drive organizational success.",
    image: "/images/home/leadership-program.png",
    imageAlt: "Leadership and management training",
    tag: "Leadership",
    tagClass: "tag-training",
    schedule: "Flexible Scheduling",
    location: "On-site / Remote",
    link: "/professional-training/leadership-management.html",
    bookingLink: "/booking.html",
    proposalLink: "/proposal.html"
  },
  {
    id: "hr-people",
    title: "HR & People Management",
    description: "Build HR teams that drive business success through effective people management strategies.",
    image: "/images/home/hr-management.png",
    imageAlt: "HR and people management training",
    tag: "HR",
    tagClass: "tag-training",
    schedule: "Flexible Scheduling",
    location: "On-site / Remote",
    link: "/professional-training/hr-people-maagement-training.html",
    bookingLink: "/booking.html",
    proposalLink: "/proposal.html"
  },
  {
    id: "finance",
    title: "Finance & Accounting",
    description: "Strengthen financial literacy across your organization with practical finance and accounting training.",
    image: "/images/home/data-analytics.png",
    imageAlt: "Finance and accounting training",
    tag: "Finance",
    tagClass: "tag-training",
    schedule: "Flexible Scheduling",
    location: "On-site / Remote",
    link: "/professional-training/finance-accounting.html",
    bookingLink: "/booking.html",
    proposalLink: "/proposal.html"
  },
  {
    id: "technology",
    title: "Technology & Data",
    description: "Professional Excel, Power BI, Python, and analytics for smarter decisions and data-driven insights.",
    image: "/images/home/data-led decisions.png",
    imageAlt: "Technology and data training",
    tag: "Technology",
    tagClass: "tag-training",
    schedule: "Flexible Scheduling",
    location: "On-site / Remote",
    link: "/professional-training/technology-data.html",
    bookingLink: "/booking.html",
    proposalLink: "/proposal.html"
  },
  {
    id: "operations",
    title: "Operations & Supply Chain",
    description: "Drive efficiency in procurement, inventory, and logistics with comprehensive operations training.",
    image: "/images/home/end-to-end-execution.png",
    imageAlt: "Operations and supply chain training",
    tag: "Operations",
    tagClass: "tag-operations",
    schedule: "Flexible Scheduling",
    location: "On-site / Remote",
    link: "/professional-training/operation-supply-chain.html",
    bookingLink: "/booking.html",
    proposalLink: "/proposal.html"
  },
  {
    id: "hse",
    title: "Health, Safety & Environment (HSE)",
    description: "Internationally recognized training for workplace safety, compliance, and environmental management.",
    image: "/images/home/compliance-by-first.png",
    imageAlt: "Health safety and environment training",
    tag: "HSE",
    tagClass: "tag-operations",
    schedule: "Flexible Scheduling",
    location: "On-site / Remote",
    link: "/professional-training/health-safety-environment.html",
    bookingLink: "/booking.html",
    proposalLink: "/proposal.html"
  },
  {
    id: "sales",
    title: "Sales & Marketing",
    description: "Cutting-edge strategies for digital growth and client acquisition with modern sales and marketing techniques.",
    image: "/images/home/digital-marketing.png",
    imageAlt: "Sales and marketing training",
    tag: "Sales",
    tagClass: "tag-training",
    schedule: "Flexible Scheduling",
    location: "On-site / Remote",
    link: "/professional-training/sales-marketing.html",
    bookingLink: "/booking.html",
    proposalLink: "/proposal.html"
  }
];


